"""update book model: add quantity

Revision ID: fac3bba1bd69
Revises: 6494b76cd907
Create Date: 2024-02-01 10:30:46.007468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac3bba1bd69'
down_revision: Union[str, None] = '6494b76cd907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'quantity')
    # ### end Alembic commands ###
